project:
  type: website
  output-dir: docs

website:
  title: "FIP606"
  navbar:
    left:
      - text: Introdução ao R
        menu: 
         - href: Aula1.qmd
           text: R markdown e data.frame
         

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

